/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * CheckoutPlus API
 * OpenAPI spec version: 0.0.1
 */

export interface PlanResponse {
  /** Unique indentifier of the plan */
  id: string;
  /** Name of the subscription plan */
  title: string;
  /** Description of the plan */
  decription: string;
  /** List of features included in the plan */
  features: string[];
  /** Monthly Price */
  monthlyPrice: number;
  /** yearlyPrice */
  yearlyPrice: string;
  /** Indicates whether the plan is featured or promoted */
  isFeatured: boolean;
}
